apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Auth and User management routes
          - path: /api/(auth|assistants|admin)/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service-ip-service
                port:
                  number: 5001
          
          # Student & Parent portal routes
          - path: /api/students/(portal|add)/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: student-service-ip-service
                port:
                  number: 5003

          # Staff & Academic management routes (Default for other /api calls)
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: staff-service-ip-service
                port:
                  number: 5002

          # Frontend routes
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-cluster-ip-service
                port:
                  number: 3000
